
export { default as CrearCuenta } from "./CrearCuenta/CrearCuenta"
export { default as Cuidados } from "./Cuidados/Cuidados"
export { default as Agendar } from "./agendar/Agendar"
export { default as Historia } from "./historia/Historia"
export { default as IniciarSeccion } from "./iniciarSeccion/IniciarSeccion"
export { default as Inicio } from "./inicio/Inicio"
export { default as Tatuadores } from "./tatuadores/Tatuadores"
export { default as ComprarProductos } from "./comprarProductos/ComprarProductos"
export { default as Tatuajes } from "./tatuajes/Tatuajes"
export { default as Perfil } from "./perfil/Perfil"
export { default as PoliticaPrivacidad } from "./politicaPrivacidad/PoliticaPrivacidad"
export { default as Ubicacion } from "./ubicacion/Ubicacion"
 export { default as Horarios } from "./horarios/Horarios"
export { default as Foro } from "./Foro/Foro"
export { default as ActualizarAgendar } from "./actualizar/ActualizarAgendar"
export { default as Borrar } from "./Borrar/Borrar"
export { default as VerMasGraficos } from "./VerMasgraficos/VerMasGraficos"
 